name: Cron

on:
  schedule:
    - cron: '20 10-18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute
        env:
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          TELEGRAM_CHAT_IDS: ${{ vars.TELEGRAM_CHAT_IDS }}
          TELEGRAM_MESSAGE_TEMPLATE: ${{ vars.TELEGRAM_MESSAGE_TEMPLATE }}
          READWISE_ACCESS_TOKEN: ${{ secrets.READWISE_ACCESS_TOKEN }}
          PUBLISHED_IDS: ${{ vars.PUBLISHED_IDS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py
